apiVersion: v2
name: "cray-hms-meds"
version: 3.1.4
description: "Kubernetes resources for cray-hms-meds"
home: "https://github.com/Cray-HPE/hms-meds-charts"
sources:
  - "https://github.com/Cray-HPE/hms-meds"
dependencies:
  - name: cray-service
    version: "~12.0"
    repository: https://artifactory.algol60.net/artifactory/csm-helm-charts
maintainers:
  - name: Hardware Management
    url: https://github.com/orgs/Cray-HPE/teams/hardware-management
appVersion: "1.26.0"
annotations:
  artifacthub.io/images: |-
    - name: cray-meds-pprof
      image: artifactory.algol60.net/csm-docker/stable/cray-meds-pprof:1.26.0
  artifacthub.io/license: "MIT"
